site_name: CS自学指南
site_url: https://cheongszesuen.github.io/ESP32-Study/
site_author: CheongSzesuen
site_description: >-
  ESP32学习指南，包含ESP32的基础知识、编程语言、开发工具、应用案例等内容，帮助读者快速入门ESP32开发。

repo_name: ESP32-Study
repo_url: https://github.com/CheongSzesuen/ESP32-Study

copyright: Copyright &copy; 2021-present <a href="https://github.com/CheongSzesuen" target="_blank" rel="noopener noreferrer">CheongSzesuen</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep blue
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep blue
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CheongSzesuen/ESP32-Study
  analytics:
    provider: google
    property: G-3TQYE4M5B9

nav:
  - 前言: "index.md"
  - 如何使用这本书: "使用指南.md"
  - 一个嵌入式开发学习规划: "CS学习规划.md"
  - 必学工具:
      - 翻墙: "必学工具/翻墙.md"
      - Vim: "必学工具/Vim.md"
      - Emacs: "必学工具/Emacs.md"
      - Git: "必学工具/Git.md"
      - GitHub: "必学工具/GitHub.md"
      - "GNU Make": "必学工具/GNU_Make.md"
      - CMake: "必学工具/CMake.md"
      - LaTeX: "必学工具/LaTeX.md"
      - Docker: "必学工具/Docker.md"
      - Scoop: "必学工具/Scoop.md"
      - 日常学习工作流: "必学工具/workflow.md"
      - 实用工具箱: "必学工具/tools.md"
      - 毕业论文: "必学工具/thesis.md"
      - 信息检索: "必学工具/信息检索.md"
  - 好书推荐: "好书推荐.md"
